name: 🐳 [FE] Build & Deploy

on:
  push:
    branches:
    - main
    # paths:
    # - "web-new/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🐳 Build apps
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      pushout: ${{ github.run_number }}
    env:
      BASE_IMAGE: "ghcr.io/waffle-id/web"
    steps:
    - name: ⬇️ Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      id: push
      with:
        context: ./web-new
        push: true
        provenance: false
        tags: ${{ env.BASE_IMAGE }}:latest,${{ env.BASE_IMAGE }}:${{ github.run_number }}

  deploy-prod:
    name: Web to Production
    if: |
      success() &&
      (github.ref == 'refs/heads/main') &&
      (github.event_name != 'workflow_dispatch')
    needs: [ build ]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: "production"
      environment-url: "https://waffle.food/"
      nomad-directory: ".deployment/nomad"
      nomad-job: "web.hcl"
      nomad-addr: "https://nomad.waffle.food"
      image-tag: ${{ needs.build.outputs.pushout }}
      module: "web"
      semver-type: minor
    secrets: inherit
